### ISSUE TITLE
Does this package work with BullMQ?

### ISSUE THREAD

**Issue by adriaandotcom** [UpHabit/bull_exporter#221]
This package seems written for [Bull from OptimalBits](https://github.com/OptimalBits/bull) but I'm wondering if it works for [BullMQ](https://github.com/taskforcesh/bullmq) by [taskforce.sh](https://taskforce.sh/) as well.

**Comment by adriaandotcom** [comment]
Let me answer my own question: after testing this on my machine with Docker, it seems to work great. It just uses a direct connection to Redis and the keys of BullMQ have the same format as Bull. This is what I use as a Docker file:

```yml
version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:6.2.5
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  bull-exporter:
    name: bull-exporter
    image: uphabit/bull_exporter:git-9acc9b2-v1.3.9 # or uphabit/bull_exporter:latest
    restart: always # restart: unless-stopped on production
    depends_on:
      - redis
    environment:
      - EXPORTER_QUEUES=my-queue-name
      - EXPORTER_REDIS_URL=redis://redis:6379/0
    ports:
      - 127.0.0.1:9538:9538
```
